[package]
name = "ceryswind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = {version = "0.17.11", features = ["rayon"]}
minifb = "0.28.0"
rand = "0.9.0"
rayon = "1.10.0"
